[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "laruco"
authors = [{name = "Dr. Vladimir Lavrik", email = "lavrikvladimir@gmail.com"}]
dynamic = ["version", "description"]
